package com.ebookmanagement.servlet;

import java.io.*;
import java.sql.*;
import javax.servlet.*;
import javax.servlet.http.*;

public class AddBookServlet extends HttpServlet {

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        PrintWriter out = response.getWriter();

        // Removed 'id' because it's auto-generated by the database
        
        String title = request.getParameter("title");
        String author = request.getParameter("author");
        String genre = request.getParameter("genre");
    
         String published_date=request.getParameter("published_date");
         String cover_img=request.getParameter("cover_img");
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Divya", "root", "root");

            // Insert without 'id' since it is auto-generated
            PreparedStatement ps = con.prepareStatement("INSERT INTO BOOK(title, author, genre,published_date,cover_img ) VALUES(?,?,?,?,?)");
            
            ps.setString(1, title);
            ps.setString(2, author);
            ps.setString(3, genre);
            ps.setString(4, published_date);
            ps.setString(5,cover_img);
            int rowsAffected = ps.executeUpdate();

            if (rowsAffected > 0) {
                out.println("<h3><font color='blue'><center>Book added successfully!</center></h3>");
            } else {
                out.println("<h3><font color='red'><center>Failed to add book.</center></h1>");
            }

            out.println("<h3><font color='blue'><center>Book added successfully!</center></font></h3>");
            RequestDispatcher rd = request.getRequestDispatcher("BookTable.jsp");
            rd.forward(request, response);
        } catch (SQLException se) {
            out.println("<h3><font color='red'><center>SQL Error: " + se.getMessage() + "</center></font></h3>");
            se.printStackTrace(out); // Consider logging instead of printing to the response
        } catch (ClassNotFoundException e) {
            out.println("<h3><font color='red'><center>Error: JDBC Driver not found!</center></font></h3>");
        } finally {
            out.close();
        }
    }
}
