package com.ebookmanagement.model;
// Generated 20 Sep, 2024 8:19:39 PM by Hibernate Tools 4.3.1



/**
 * Ebooks generated by hbm2java
 */
public class Ebooks  implements java.io.Serializable {


     private int id;
     private String title;
     private String author;
     private String genre;
     private String CPdf;
     private String coverImg;

    public Ebooks() {
    }

	
    public Ebooks(int id, String title, String author, String genre) {
        this.id = id;
        this.title = title;
        this.author = author;
        this.genre = genre;
    }
    public Ebooks(int id, String title, String author, String genre, String CPdf, String coverImg) {
       this.id = id;
       this.title = title;
       this.author = author;
       this.genre = genre;
       this.CPdf = CPdf;
       this.coverImg = coverImg;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }
    public String getCPdf() {
        return this.CPdf;
    }
    
    public void setCPdf(String CPdf) {
        this.CPdf = CPdf;
    }
    public String getCoverImg() {
        return this.coverImg;
    }
    
    public void setCoverImg(String coverImg) {
        this.coverImg = coverImg;
    }




}


